version: "3.2"
services:
  apache:
    build: "./docker/dev/apache"
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html
      - ${VHOSTS_DIR}:/etc/apache2/sites-enabled
      - ${LOG_DIR}:/var/log/apache2
      - ${PHP_INI}:/usr/local/etc/php/php.ini
  mysql:
    build: "./docker/dev/mysql"
    container_name: '5.6.40-mysql'
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${MYSQL_LOG_DIR}:/var/log/mysql
  phpmyadmin:
    container_name: 'sc-phpmyadmin'
    build: "./docker/dev/phpmyadmin"
    links:
      - mysql
    ports:
      - '8080:80'
    volumes: 
      - /sessions
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}